services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - mynet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  tasks-service:
    image: tasks-service:1.0-SNAPSHOT
    container_name: tasks_service
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "9000:9000"
    command:
      - "-Dplay.server.pidfile.path=/dev/null"
      - "-Dslick.dbs.default.db.url=jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
      - "-Dslick.dbs.default.db.user=${MYSQL_USER}"
      - "-Dslick.dbs.default.db.password=${MYSQL_PASSWORD}"
      - "-Dplay.http.secret.key=${PLAY_HTTP_SECRET_KEY}"
      - "-Dnotification.service.host=notification-service"

    volumes:
      - ./logs:/opt/docker/logs
      - ./tasks-service/certs:/app/certs:ro    # task’s own certs (read-only)
      - ./certs:/app/ca:ro                     # common CA (read-only)


    networks:
      - mynet

  notification-service:
    image: notification-service:0.1.0
    container_name: notification_service
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "50051:50051"
    command:
      - "-Ddb.default.url=jdbc:mysql://mysql:3306/notificationdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
      - "-Ddb.default.user=notifyUser"
      - "-Ddb.default.password=notifyPassword"

    volumes:
      - ./notification-service/certs:/app/certs:ro  # server’s own certs
      - ./certs:/app/ca:ro                         # root CA shared

    networks:
      - mynet

volumes:
  mysql-data:

networks:
  mynet:
