name: Scala CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  # Job 1: Build notification-proto once
  build-proto:
    name: Build notification-proto
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'sbt'

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Build and Publish notification-proto
        working-directory: ./notification-proto
        run: |
          echo "Building notification-proto..."
          sbt clean compile publishLocal
          echo "Proto published successfully"
          echo "Checking Ivy local cache..."
          ls -la ~/.ivy2/local/com.example/

      # Cache the proto artifacts for service jobs
      - name: Cache Proto Artifacts
        uses: actions/cache/save@v4
        with:
          path: ~/.ivy2/local
          key: proto-${{ github.sha }}

  # Job 2: Build and test services (runs after proto is built)
  build-and-test:
    name: ${{ matrix.service.name }} CI
    runs-on: ubuntu-latest
    needs: build-proto  # Wait for proto job to complete
    strategy:
      fail-fast: false
      matrix:
        service:
          - { name: "notification-service", dir: "notification-service" }
          - { name: "tasks-service", dir: "tasks-service" }

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'sbt'

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      # Restore proto artifacts from cache
      - name: Restore Proto Artifacts
        uses: actions/cache/restore@v4
        with:
          path: ~/.ivy2/local
          key: proto-${{ github.sha }}
          fail-on-cache-miss: true

      - name: Verify Proto Available
        run: |
          echo "Checking for proto artifacts in Ivy cache..."
          ls -la ~/.ivy2/local/com.example/ || echo "ERROR: Proto not found in cache!"

      # --- Per-Service Steps ---

      - name: Check code formatting
        working-directory: ./${{ matrix.service.dir }}
        run: sbt scalafmtCheckAll scalafmtSbtCheck

      - name: Compile code
        working-directory: ./${{ matrix.service.dir }}
        run: sbt compile Test/compile

      - name: Run tests with coverage
        working-directory: ./${{ matrix.service.dir }}
        run: sbt coverage test coverageReport

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          files: ./${{ matrix.service.dir }}/target/scala-2.13/scoverage-report/scoverage.xml
          flags: ${{ matrix.service.name }}
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run static analysis
        working-directory: ./${{ matrix.service.dir }}
        run: sbt scapegoat
        continue-on-error: true

      - name: Archive static analysis report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.service.name }}-scapegoat-report
          path: ./${{ matrix.service.dir }}/target/scala-2.13/scapegoat-report/
          if-no-files-found: warn