name: Scala CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Job 1: Build and test tasks-service
  tasks-service:
    name: Tasks Service CI
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup JDK
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'sbt'

      # Step 3: Install sbt
      - name: Install sbt
        run: |
          curl -L -o sbt.deb https://scala.jfrog.io/artifactory/debian/sbt-1.9.8.deb
          sudo dpkg -i sbt.deb
          sudo apt-get update
          sudo apt-get install sbt

      # Step 4: Check formatting
      - name: Check code formatting
        working-directory: ./tasks-service
        run: sbt scalafmtCheckAll scalafmtSbtCheck

      # Step 5: Compile
      - name: Compile code
        working-directory: ./tasks-service
        run: sbt compile Test/compile

      # Step 6: Run tests with coverage
      - name: Run tests with coverage
        working-directory: ./tasks-service
        run: sbt coverage test coverageReport

      # Step 7: Upload coverage
      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          files: ./tasks-service/target/scala-2.13/scoverage-report/scoverage.xml
          flags: tasks-service
          fail_ci_if_error: false

      # Step 8: Run scapegoat
      - name: Run static analysis
        working-directory: ./tasks-service
        run: sbt scapegoat
        continue-on-error: true

      # Step 9: Archive scapegoat report
      - name: Archive static analysis report
        uses: actions/upload-artifact@v4
        with:
          name: tasks-service-scapegoat-report
          path: ./tasks-service/target/scala-2.13/scapegoat-report/

  # Job 2: Build and test notification-service
  notification-service:
    name: Notification Service CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'sbt'

      - name: Install sbt
        run: |
          curl -L -o sbt.deb https://scala.jfrog.io/artifactory/debian/sbt-1.9.8.deb
          sudo dpkg -i sbt.deb
          sudo apt-get update
          sudo apt-get install sbt

      - name: Check code formatting
        working-directory: ./notification-service
        run: sbt scalafmtCheckAll scalafmtSbtCheck

      - name: Compile code
        working-directory: ./notification-service
        run: sbt compile Test/compile

      - name: Run tests with coverage
        working-directory: ./notification-service
        run: sbt coverage test coverageReport

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          files: ./notification-service/target/scala-2.13/scoverage-report/scoverage.xml
          flags: notification-service
          fail_ci_if_error: false

      - name: Run static analysis
        working-directory: ./notification-service
        run: sbt scapegoat
        continue-on-error: true

      - name: Archive static analysis report
        uses: actions/upload-artifact@v4
        with:
          name: notification-service-scapegoat-report
          path: ./notification-service/target/scala-2.13/scapegoat-report/
